window.decorations = "full"
window.dynamic_title = true

[env]
TERM = "xterm-256color"

[window.padding]
x = 6
y = 6

[general]
import = [
    "./themes/themes/gruvbox_material_hard_dark.toml"
]

### Font configuration
[font]
size = 12.0

# [font.bold]
# family = "JetBrainsMono NFP"
# style = "Bold"

# [font.bold_italic]
# family = "JetBrainsMono NFP"
# style = "Bold Italic"

# [font.italic]
# family = "JetBrainsMono NFP"
# style = "Italic"

# [font.normal]
# family = "JetBrainsMono NFP"
# style = "Regular"

